name: daily_astropic
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  youtube_player_flutter: ^8.1.2
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  envied: ^0.5.4+1
  go_router: ^14.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true
  assets:
    - assets/


